# Generated by Django 4.2 on 2023-04-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author_blog_date_added_blog_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_updated',
        ),
    ]
