# Generated by Django 4.2 on 2023-05-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_updated',
        ),
    ]
