# Generated by Django 4.2 on 2023-05-06 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_date_added_remove_blog_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
