# Generated by Django 4.2 on 2023-04-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
